version: '3.4'

services:
 sqldata:
  image: mcr.microsoft.com/mssql/server:2019-latest
  environment:
   - SA_PASSWORD=Pass@word
   - ACCEPT_EULA=Y
  ports:
   - "1433:1433"
  volumes:
   - tareas-sqldata:/var/opt/mssql
volumes:
 tareas-sqldata:
  external: false