CREATE DATABASE PAGOS;
GO

USE PAGOS

GO
CREATE TABLE MediosPago (
Id INT IDENTITY,
DesMedioPago NVARCHAR(50),
IndEstadoMedioPago BIT 
);

GO
CREATE TABLE Pago (
Id INT IDENTITY,
CodCarrito INT,
Valor DECIMAL (12,2),
FechaPago DATETIME,
IndEstadoPago DECIMAL (1)
);

GO
INSERT INTO MediosPago VALUES ('PSE',1)
INSERT INTO MediosPago VALUES ('TARJETA DE CRÉDITO',2)

GO
INSERT INTO Pago VALUES (1,356000,DATEADD(hh,-5,DATEADD(yy,-1,GETDATE())),1)
INSERT INTO Pago VALUES (2,1356000,DATEADD(hh,-5,DATEADD(yy,-2,GETDATE())),1)
INSERT INTO Pago VALUES (3,130356000,DATEADD(hh,-5,DATEADD(mm,-10,GETDATE())),0)
INSERT INTO Pago VALUES (4,20000.1,DATEADD(hh,-5,GETDATE()),1)

GO
SELECT * FROM MediosPago
SELECT * FROM Pago