CREATE DATABASE PRECIOS;
GO

USE PRECIOS

CREATE TABLE Intercambio (
Id INT IDENTITY,
CodMoneda NVARCHAR(3),
DesMoneda NVARCHAR(50),
ValUSD DECIMAL(20,10),
);

GO
CREATE TABLE Pais (
Id INT IDENTITY,
CodPais NVARCHAR(3),
DesPais NVARCHAR(50)
);

GO
CREATE TABLE Impuesto (
Id INT IDENTITY,
DesImpuesto NVARCHAR(50),
CodPais NVARCHAR(3),
Valor DECIMAL (10,2)
);

GO
INSERT INTO Intercambio VALUES ('USD','DOLAR',0.0002713821)
INSERT INTO Intercambio VALUES ('EUR','EURO',0.0002236268)
INSERT INTO Intercambio VALUES ('ARS','PESOS ARGENTINOS',0.02548957)
INSERT INTO Intercambio VALUES ('BOB','BOLIVIANO',0.0018675885)
INSERT INTO Intercambio VALUES ('BRL','REAL BRAZILERO',0.0014305426)
INSERT INTO Intercambio VALUES ('CLP','PESO CHILENO',0.18990548)
INSERT INTO Intercambio VALUES ('COP','PESO COLOMBIANO',1)
INSERT INTO Intercambio VALUES ('PYG','GUARANY PARAGUAYO',1.8289249)
INSERT INTO Intercambio VALUES ('PEN','SOL PERUANO',0.0009999625)
INSERT INTO Intercambio VALUES ('UYU','PESO URUGUAYO',0.011992071)
INSERT INTO Intercambio VALUES ('VES','BOLIVAR VENEZOLANO',788.0802)
INSERT INTO Intercambio VALUES ('GBP','LIBRAS ESTERLINAS',0.0001926535)
INSERT INTO Intercambio VALUES ('MNX','PESO MEXICANO',0.0054075051)

GO
INSERT INTO Pais VALUES ('USA','ESTADOS UNIDOS')
INSERT INTO Pais VALUES ('ESP','ESPAÑA')
INSERT INTO Pais VALUES ('ARG','ARGENTINA')
INSERT INTO Pais VALUES ('BOL','BOLIVIA')
INSERT INTO Pais VALUES ('BRA','BRASIL')
INSERT INTO Pais VALUES ('CHL','CHILE')
INSERT INTO Pais VALUES ('COL','COLOMBIA')
INSERT INTO Pais VALUES ('PRY','PARAGUAY')
INSERT INTO Pais VALUES ('PER','PERU')
INSERT INTO Pais VALUES ('URY','URUGUAY')
INSERT INTO Pais VALUES ('VEN','VENEZUELA')
INSERT INTO Pais VALUES ('GRB','REINO UNIDO')
INSERT INTO Pais VALUES ('MEX','MEXICO')

GO
INSERT INTO Impuesto VALUES ('TAX EU','USA',1)
INSERT INTO Impuesto VALUES ('TAX ESPAÑA','ESP',2)
INSERT INTO Impuesto VALUES ('TAX ARGENTINA','ARG',1)
INSERT INTO Impuesto VALUES ('TAX BOLIVIA','BOL',1)
INSERT INTO Impuesto VALUES ('TAX BRASIL','BRA',2)
INSERT INTO Impuesto VALUES ('TAX CHILE','CHL',1)
INSERT INTO Impuesto VALUES ('IVA COLOMBIA','COL',3)
INSERT INTO Impuesto VALUES ('TAX PARAGUAY','PRY',1)
INSERT INTO Impuesto VALUES ('TAX PERU','PER',2)
INSERT INTO Impuesto VALUES ('TAX URUGUAY','URY',1)
INSERT INTO Impuesto VALUES ('TAX VENEZUELA1','VEN',1)
INSERT INTO Impuesto VALUES ('TAX VENEZUELA2','VEN',4)
INSERT INTO Impuesto VALUES ('TAX MEXICO','MEX',2)


ALTER TABLE Pais ADD IndEstado BIT;
ALTER TABLE PAIS ADD CodMoneda nvarchar(3);
GO

UPDATE Pais SET INDESTADO=0
UPDATE Pais SET INDESTADO=1 WHERE ID IN(6,7,9,13)
UPDATE Pais SET CodMoneda= CASE 
                           WHEN CodPais='USA' THEN 'USD'
                           WHEN CodPais='ESP' THEN 'EUR'
                           WHEN CodPais='ARG' THEN 'ARS'
                           WHEN CodPais='BOL' THEN 'BOB'
                           WHEN CodPais='BRA' THEN 'BRL'
                           WHEN CodPais='CHL' THEN 'CLP'
                           WHEN CodPais='COL' THEN 'COP'
                           WHEN CodPais='PRY' THEN 'PYG'
                           WHEN CodPais='PER' THEN 'PEN'
                           WHEN CodPais='URY' THEN 'UYU'
                           WHEN CodPais='VEN' THEN 'VES'
                           WHEN CodPais='GRB' THEN 'GBP'
                           WHEN CodPais='MEX' THEN 'MXN'
                           END

GO
SELECT * FROM Intercambio
SELECT * FROM Pais
SELECT * FROM Impuesto