CREATE DATABASE PRECIOS;
GO

USE PRECIOS

CREATE TABLE INTERCAMBIO (
Id INT IDENTITY,
CodMoneda NVARCHAR(3),
DesMoneda NVARCHAR(50),
ValUSD DECIMAL (20,10),
);

GO

INSERT INTO INTERCAMBIO VALUES ('USD','DOLAR',1)
INSERT INTO INTERCAMBIO VALUES ('EUR','EURO',0.82662)
INSERT INTO INTERCAMBIO VALUES ('ARS','PESOS ARGENTINOS',93.1443)
INSERT INTO INTERCAMBIO VALUES ('BOB','BOLIVIANO',6.93)
INSERT INTO INTERCAMBIO VALUES ('BRL','REAL BRAZILERO',5.4763)
INSERT INTO INTERCAMBIO VALUES ('CLP','PESO CHILENO',712.6)
INSERT INTO INTERCAMBIO VALUES ('COP','PESO COLOMBIANO',3623.76)
INSERT INTO INTERCAMBIO VALUES ('PYG','GUARANY PARAGUAYO',6442.07)
INSERT INTO INTERCAMBIO VALUES ('PEN','SOL PERUANO',3.7785)
INSERT INTO INTERCAMBIO VALUES ('UYU','PESO URUGUAYO',44.1018)
INSERT INTO INTERCAMBIO VALUES ('VES','BOLIVAR VENEZOLANO',2573881.14)
INSERT INTO INTERCAMBIO VALUES ('GBP','LIBRAS ESTERLINAS',0.72051)

SELECT * FROM INTERCAMBIO

--TRUNCATE TABLE INTERCAMBIO